"""user jwt

Revision ID: 738e85ff7561
Revises: 3fd390f99c57
Create Date: 2020-05-29 14:20:25.873847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738e85ff7561'
down_revision = '3fd390f99c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token')
        batch_op.drop_column('token_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
